import type { Metadata } from "next";
import { Anton, Pirata_One} from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const anton = Anton({
  variable: "--font-vietnam",
  weight: "400",
  subsets: ["latin"],
});

const pirata = Pirata_One({
  variable: "--font-pirata",
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Bajo tierra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${pirata.variable} antialiased bg-customized text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
